yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'


urlpatterns = [
    path('author/',
         views.AboutAuthorView.as_view(),
         name='author'),
    path('tech/',
         views.AboutTechView.as_view(),
         name='tech'),

]

yatube/api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import PostViewSet

router = routers.DefaultRouter()
router.register(r'posts', PostViewSet)

urlpatterns = [
    path('', include(router.urls))
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',
         views.index,
         name='index'),
    path('group/<slug:slug>/',
         views.group_posts,
         name='group_list'),
    path('posts/<int:post_id>/edit/',
         views.post_edit,
         name='post_edit'),
    path('profile/<str:username>/',
         views.profile,
         name='profile'),
    path('posts/<int:post_id>/',
         views.post_detail,
         name='post_detail'),
    path('create/',
         views.post_create,
         name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/',
         views.follow_index,
         name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
    path('authors_follow/',
         views.authors_follow,
         name='authors_follow'),

]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, \
    LogoutView, \
    PasswordResetView, \
    PasswordChangeView
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path('signup/',
         views.SignUp.as_view(),
         name='signup'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('password_reset_form/',
         PasswordResetView.as_view(
             template_name='/password_reset_form.html'),
         name='password_reset_form'),
    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html'),
         name='password_change'),
    path('password_change/done',
         PasswordChangeView.as_view(
             template_name='users/password_change_done.html'),
         name='password_change_done')

]

yatube/api/models.py
from django.db import models

# Create your models here.

yatube/core/models.py
from django.db import models


class CreatedModel(models.Model):
    created = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        abstract = True

yatube/posts/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(help_text='Введите текст поста',
                            verbose_name='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts')
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        help_text='Выберите группу',
        verbose_name='Группа',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
    )
    file = models.FileField(
        'Текст поста можно загрузить из файла',
        upload_to='file/',
        blank=True,

    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE)
    text = models.TextField(help_text='Напишите комментарий',
                            verbose_name='Комментарий')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE)
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'author',)

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image', 'file',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta (UserCreationForm.Meta):
        model = User
        fields = ('first_name',
                  'last_name',
                  'username',
                  'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/api/views.py
from posts.models import Post
from rest_framework import viewsets

from .serializer import PostSerializer


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

yatube/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    # Переменная exception содержит отладочную информацию;
    # выводить её в шаблон пользовательской страницы 404 мы не станем
    return render(request,
                  'core/404.html',
                  {'path': request.path},
                  status=404)


def server_error(request):
    return render(request,
                  'core/500.html',
                  status=500)


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

yatube/posts/views.py
from django.shortcuts import render, \
    get_object_or_404, redirect
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from .utils import make_paginator, read_file
from django.views.decorators.cache import cache_page
from django.conf import settings
import os


@cache_page(20)
def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()
    context = {
        'page_obj': make_paginator(request, posts),
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        'page_obj': make_paginator(request, posts),
        'group': group,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = User.objects.get(username=username)
    posts = author.posts.all()
    following = (request.user.is_authenticated
                 and author.following.filter(user=request.user)
                 .exists()
                 )

    context = {
        'page_obj': make_paginator(request, posts),
        'author': author,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    author = User.objects.get(posts=post_id)
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    file = post.file

    context = {
        'post': post,
        'author': author,
        'comments': comments,
        'form': form,
        'text_file': read_file(file),
    }
    return render(request, template, context)


@login_required
def post_create(request):
    form = PostForm(request.POST)
    template = 'posts/create_post.html'
    context = {
        'form': form,
    }
    if request.method == 'POST':
        form = PostForm(request.POST or None,
                        request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author.username)
        return render(request, template, context)
    else:
        return render(request, template, context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user.id != post.author.id:
        return redirect('posts:post_detail', post_id=post.id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        post.author = request.user
        post.save()
        return redirect('posts:post_detail', post_id=post.id)
    context = {
        'form': form,
        'is_edit': True,
        'post_id': post_id
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    context = {
        'page_obj': make_paginator(request, posts),
    }
    template = 'posts/follow.html'
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    if request.user.username != username:
        following = get_object_or_404(User, username=username)
        Follow.objects.get_or_create(user=request.user,
                                     author=following)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    following = User.objects.get(username=username)
    follower = get_object_or_404(Follow,
                                 author=following,
                                 user=request.user)
    follower.delete()
    return redirect('posts:profile', username=username)


@login_required
def authors_follow(request):
    posts = Post.objects.filter(author__following__user=request.user)
    context = {
        'posts': posts,
    }
    template = 'posts/authors_follow.html'
    return render(request, template, context)

yatube/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/includes/add_comment.html
{% load user_filters %}
{% if user.is_authenticated %}
<div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}
            <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>
</div>
{% endif %}

{% for comment in comments %}
<div class="media mb-4">
    <div class="media-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
            </a>
        </h5>
        <p>
            {{ comment.text }}
        </p>
    </div>
</div>
{% endfor %}

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<header>
    <nav class="navbar navbar-light" style="background-color: indigo">
        <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
                <img src=" {% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                <b style="color:white">Yatube</b>
            </a>
            {% with request.resolver_match.view_name as view_name %}
            <ul class="nav nav-pills" >
                <li class="nav-item" style="color: indigo">
                    <a class="nav-link {% if view_name  == 'about:author' %} active {% endif %}"
                       href="{% url 'about:author' %}">Об авторе</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view_name  == 'about:tech' %} active {% endif %}"
                       href="{% url 'about:tech' %}">Технологии</a>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item" style="background-color: indigo">
                    <a class="nav-link" href="{% url 'posts:post_create' %}">Новая запись</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light {% if view_name  == 'users:password_change' %} active {% endif %}"
                       href="{% url 'users:password_change' %}">Изменить пароль</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light {% if view_name  == 'users:logout' %} active {% endif %}"
                       href="{% url 'users:logout' %}">Выйти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" style="color:blue">
                        Пользователь: {{ user.username }}</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link link-light {% if view_name  == 'users:login' %} active {% endif %}"
                       href="{% url 'users:login' %}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link link-light {% if view_name  == 'users:signup' %} active {% endif %}"
                       href="{% url 'users:signup' %}">Регистрация</a>
                </li>
                {% endif %}
            </ul>
            {% endwith %}
        </div>
    </nav>
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/post.html
{% load thumbnail %}
<article>
    <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img src="{{ im.url }}">
    {% endthumbnail %}
    <div class="container">
        <br>
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    </div>
</article>


yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
<div class="row my-3">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a
                    class="nav-link {% if index %}active{% endif %}"
                    href="{% url 'posts:index' %}"
            >
                Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a
                    class="nav-link {% if follow %}active{% endif %}"
                    href="{% url 'posts:follow_index' %}"
            >
                Избранные авторы
            </a>
        </li>
        <li class="nav-item">
            <a
                    class="nav-link "
                    href="{% url 'posts:authors_follow' %}"
            >
                Подписки
            </a>
        </li>
    </ul>
</div>
{% endif %}